api_active: 1
api_darksky: null
api_fpt: null
domain: https://
google_application_credentials: hehe.cucu
hass_password: pass
hotword: subex
led_do: 15
led_xanh: 14
longlived-token: cl1teS2AX4
model: subex.umdl
reminder: 1
sensitivity: 0.9
version_above084: right
voice: male
